name: Generate README.md to serve
on:
  workflow_dispatch:
    inputs:
        header:
          description: 'Заголовок страницы'
          required: false
        pictureExtensions:
          description: 'Расширение файлов картинок'
          required: false
          type: choice
          options:
          - ""
          - .png
          - .jpg
          - .jpeg
jobs:
  generator:
    runs-on: ubuntu-latest
    env:
      header: ${{ inputs.header }}
      pictureExtensions: ${{ inputs.pictureExtensions }}
      nameAndRepo: ${{ github.repository }}  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: |
        cd readme-generator
        
        runnable=true
        if [ -z "$header" ] && [ -z "$pictureExtensions" ] && ( [ -s ../.github/workflows/header.txt ] || [ -s ../.github/workflows/extensions.txt ] ); then runnable=false; fi        
        if [ -z "$header" ]; then header=$(cat ../.github/workflows/header.txt); fi
        if [ -z "$pictureExtensions" ]; then pictureExtensions=$(cat ../.github/workflows/extensions.txt); fi
        
        echo "$header" > ../.github/workflows/header.txt
        echo "$pictureExtensions" > ../.github/workflows/extensions.txt

        githubName=$(echo $nameAndRepo | cut -d '/' -f 1)
        repo=$(echo $nameAndRepo | cut -d '/' -f 2)
        
        echo "$runnable"
        echo "header: $header"
        echo "pictureExtensions: $pictureExtensions"
        echo "name: $githubName"
        echo "repo: $repo"
        
        
        
        if [ "$runnable" -eq "false" ]; then echo "can't run!"; else python generator.py "$githubName" "$repoName" "$header" "$pictureExtensions"; cd ../; git commit -am "generating README.md"; git push; fi
      
